default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
  - repo: https://github.com/SethAngell/semantic-commit-formatter
    rev: v1
    hooks:
      - id: semantic_commit
        stages: [prepare-commit-msg]
        args: ["--log", "--strict"]
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
